---
- name: Init master
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version={{ k8s_version }}
  register: kubeadm_init

- fail:
    msg: "kubeadm init command failed."
  when: kubeadm_init.stdout.find ("kubeadm join") == -1

- name: Store kubeadm join string
  set_fact:
    join_str: "{{ kubeadm_init.stdout | regex_search('kubeadm join(.*)$') }}"

- name: Prepare kube config
  shell: mkdir -p {{ item }}/.kube && cp -a /etc/kubernetes/admin.conf {{ item }}/.kube/config
  with_items:
    - "{{ ansible_env.HOME }}"
    - /home/ubuntu

- name: Allow pod on master
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-

- name: Download calico yaml
  get_url:
    url: https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
    dest: "{{ ansible_env.HOME }}/calico.yaml"
    force: no

- name: Change calico config
  replace:
    path: "{{ ansible_env.HOME }}/calico.yaml"
    regexp: 'value: "always"'
    replace: 'value: "off"\n            - name: CALICO_IPV4POOL_NAT_OUTGOING\n              value: "true"'
    backup: yes

- name: Install network plugin
  shell: kubectl apply -f {{ ansible_env.HOME }}/calico.yaml
