---
- name: Create temporary directory
  file:
    state: directory
    path: ~/kube-prompt
  register: dir

- name: Download kube-prompt
  get_url:
    url: https://github.com/c-bata/kube-prompt/releases/download/v1.0.3/kube-prompt_v1.0.3_linux_amd64.zip
    dest: "{{ dir.path }}/kube-prompt_v1.0.3_linux_amd64.zip"
    force: no

- name: Unarchive kube-prompt
  unarchive:
    src: "{{ dir.path }}/kube-prompt_v1.0.3_linux_amd64.zip"
    dest: "{{ dir.path }}"
    remote_src: yes
    creates: "{{ dir.path }}/kube-prompt"

- name: copy kube-prompt to /usr/bin
  copy:
    src: "{{ dir.path }}/kube-prompt"
    dest: /usr/bin/kube-prompt
    remote_src: yes
    force: no

- name: create alias for kube-prompt
  lineinfile:
    path: /etc/bash.bashrc
    create: true
    line: 'alias kp="/usr/bin/kube-prompt"'
